version: '3'
services:
  db:
    image: postgres:13-alpine
    container_name: db
    env_file:
      - .env
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./config/db/ggl_db.sql:/docker-entrypoint-initdb.d/init.sql

  app_gglsheets:
    build:
      context: .
      dockerfile: config/app_gglsheets/Dockerfile
    container_name: app_gglsheets
    working_dir: /var/www/gglsheets_admin
    volumes:
      - ./gglsheets:/var/www/gglsheets_admin
    depends_on:
      - db
    networks:
      - app-network
    env_file:
      - .env
    entrypoint: /usr/local/bin/entrypoint.sh

  app_ggl:
    build:
      context: .
      dockerfile: config/ggl_to_post/Dockerfile
    container_name: app_ggl
    working_dir: /opt/ggl/
    volumes:
      - ./ggl_to_psql:/opt/ggl/
    networks:
      - app-network
    env_file:
      - .env
    depends_on:
      - db
    command: python main.py

networks:
  app-network:
    driver: bridge

volumes:
  app_gglsheets:
  db_data: