# Generated by Django 3.2.13 on 2022-06-27 23:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sheets_content',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('num', models.IntegerField(verbose_name='№')),
                ('order_number', models.IntegerField(verbose_name='заказ №')),
                ('price_usd', models.FloatField(verbose_name='стоимость,$')),
                ('price_rub', models.FloatField(verbose_name='стоимость,Р')),
                ('delivery_date', models.DateField(verbose_name='срок поставки')),
            ],
            options={
                'verbose_name': 'Гугл таблица',
                'verbose_name_plural': 'Гугл таблица',
                'db_table': 'content"."sheets_content',
            },
        ),
    ]
